### ISSUE TITLE
Power_use showing NaN

### ISSUE THREAD

**Issue by djansen1987** [cyberjunky/home-assistant-toon_smartmeter#13]
Dear,

Let me start of with being very happy with all the work you did.
I got my rooted toon running for some time now but do not get any values on the power_use.

Is this an known issue or am i doing something wrong?
Thanks!

![image](https://user-images.githubusercontent.com/20375973/102694809-b56c6300-4223-11eb-8868-662a0fb7fdc6.png)

**Comment by cyberjunky** [comment]
@djansen1987 It's fine, it's returned by your Toon because you connected the P1 smart-meter, those two are for the Analog pulse counters which are not connected. So you should remove them from the resources: section of you config. There is however another issue with NaN or nan, and thats that HA is not happy with them (for example during restarts on active sensors) so I make a note to replace them with None values.

Remove these:
```
  - sensor.toon_power_use_cnt
  - sensor.toon_power_use
```

**Comment by djansen1987** [comment]
Hi @cyberjunky ,

Thanks for replying so quickly. Is there any way to see the current power use with the P1?
I know i can see it by the power use low and high but i was looking for 1 sensor that represents the usage no matter if the tariff is high or low? This so i can hook up an gauge or graph to it. 

Thanks a lot!

**Comment by cyberjunky** [comment]
Sure, you can make a template sensor like this:
```
  - platform: template
    sensors:
      stroom_verbruik:
        friendly_name: "Stroom Verbruik"
        unit_of_measurement: "Watt"
        value_template: >
          {{ ( (states('sensor.toon_p1_power_use_low')|float) + (states('sensor.toon_p1_power_use_high')|float) ) }}
      stroom_levering:
        friendly_name: "Stroom Levering"
        unit_of_measurement: "Watt"
        value_template: >
          {{ ( (states('sensor.toon_p1_power_prod_low')|float) + (states('sensor.toon_p1_power_prod_high')|float) ) }}
```
