### ISSUE TITLE
create compatibility with new HA (2021.8) Energy Management integration

### ISSUE THREAD

**Issue by Bart-1992** [cyberjunky/home-assistant-toon_smartmeter#23]
Would be nice if the entities from this custom-integration could be used as entities within the new HA 2021.8 Energy management intergration and dashboard: 
[https://www.home-assistant.io/docs/energy/](url)

**Comment by freddieleeman** [comment]
For now, if people want to add the sensors to the Home Assistant Energy dashboard, add the following code to your configuration.yaml:

```
homeassistant:
  customize_glob:
    sensor.toon_p1_power_*_cnt_*:
      device_class: energy
      state_class: measurement
      last_reset: "1970-01-01T00:00:00+00:00"
```
