### ISSUE TITLE
HA energy dashboard can't see sensor.toon_p1_power_use_high

### ISSUE THREAD

**Issue by multispeed** [cyberjunky/home-assistant-toon_smartmeter#64]
HI,

I am trying to add the sensor.toon_p1_power_use_high to my energy dashboard, but it's not available in the ebergy dashboard sensor list. (image 1+2)

It is available as a lovelace sensor though (image3)

This is my configuration

```
  - platform: toon_smartmeter
    host: 192.168.2.78
    port: 80
    scan_interval: 10
    resources:
      - elecusageflowpulse
      - elecusagecntpulse
      - elecusageflowlow
      - elecusagecntlow
      - elecusageflowhigh
      - elecusagecnthigh
```

![image](https://user-images.githubusercontent.com/22557639/201638951-d469d44f-b6c4-4511-89e3-ba3bd19a209b.png)

![image](https://user-images.githubusercontent.com/22557639/201639082-e2154b9a-e87b-4c0a-afde-d1018dbc2b89.png)

![image](https://user-images.githubusercontent.com/22557639/201639117-dfbfc651-25b3-4019-be9d-910f10a2fc1e.png)
