### ISSUE TITLE
Gas used last hour

### ISSUE THREAD

**Issue by butanon2** [cyberjunky/home-assistant-toon_smartmeter#70]
Hi,

I want to use  "Gas used today"

Is this possible to adjust this option in the code?

**Comment by DennisDeKoster** [comment]
I would like this too, Toon has a tile with gas today. Gas last hour isn't very helpful. 
Is it possible to add this?

**Comment by DennisDeKoster** [comment]
Never mind, I found a way to store the gas used value at midnight and calculate todays usage.

**Comment by DennisDeKoster** [comment]
If someone would like to use this, here's my solution:

1. Create a numeric helper, in my case `input_number.gasmeter_stand_gisteren`

2. Make an automation to store the current gas usage at midnight.

```
alias: Gasmeter stand opslaan
description: ""
trigger:
  - platform: time
    at: "23:59:59"
condition: []
action:
  - service: input_number.set_value
    data:
      value: "{{ states('sensor.toon_gas_used_cnt') }}"
    target:
      entity_id: input_number.gasmeter_stand_gisteren
    alias: Onthoud gasmeterstand
mode: single
```

3. Then add this template sensor to the configuration.yaml and use this new entity `sensor.gas_verbruik_vandaag` in your dashboard.

```
sensor:
  - platform: template
    sensors:
      gas_verbruik_vandaag:
        friendly_name: "Gasverbruik vandaag"
        unit_of_measurement: 'm3'
        icon_template: mdi:meter-gas
        value_template: "{{ (states('sensor.toon_gas_used_cnt') | float - states('input_number.gasmeter_stand_gisteren') | float) | round(2)}}"
```
