### ISSUE TITLE
Feature request: Merge current power usage high and low into one

### ISSUE THREAD

**Issue by HealthyFridge** [cyberjunky/home-assistant-toon_smartmeter#73]
Currently there are two indicators for current power usage: one is used during 'day' hours, and one during 'night' hours. 
I think it would be useful to also have a combined sensor that shows current power usage throughout the whole day.
Just like what is shown on the Toon tile.

Anyone else who would like this feature? (or maybe I missed some trick to get the same effect on my dashboard)

**Comment by DennisDeKoster** [comment]
I came to the same conclusion when I saw 0,00 in Home Assistant at daytime (added this in the evening). Forgot about the high and low meters. But in HA you can create a template sensor and combine the two (just add them together, because one will always be zero).

You can add this to the configuration.yaml:

```
sensor:
  - platform: template
    sensors:
      energie_verbruik_totaal:
        friendly_name: "Energieverbruik"
        unit_of_measurement: 'W'
        icon_template: mdi:lightning-bolt
        value_template: "{{ states('sensor.toon_p1_power_use_low') | int + states('sensor.toon_p1_power_use_high') | int }}"
```

And then use this new entity in your dashboard card.
